"""
Report Writer Agent
Takes structured insights from the Analyst and produces a polished,
markdown-formatted research report.
"""

from datetime import datetime
from typing import Any, Dict, List

from agents.base_agent import BaseAgent


WRITER_SYSTEM_PROMPT = """You are a professional technical writer who specializes in
creating clear, well-structured research reports. You excel at:
- Writing compelling executive summaries
- Organizing information logically under meaningful headings
- Making complex topics accessible to a general professional audience
- Ending reports with actionable conclusions and recommendations

Write in a clear, professional tone. Use markdown formatting.
"""


class ReportWriterAgent(BaseAgent):
    """
    Agent 3 — Report Writer
    Produces a final, polished research report in Markdown format.
    """

    def __init__(self, groq_api_key: str):
        super().__init__(
            groq_api_key=groq_api_key,
            temperature=0.4,
            max_tokens=4000,
        )

    @property
    def role(self) -> str:
        return "Technical Report Writer"

    @property
    def goal(self) -> str:
        return (
            "Compile research insights into a clear, well-structured, "
            "professional report that delivers genuine value to the reader."
        )

    @property
    def backstory(self) -> str:
        return (
            "You are an award-winning technical writer who has produced hundreds "
            "of research reports for Fortune 500 companies. Your reports are "
            "known for being concise yet comprehensive, and always actionable."
        )

    def run(self, inputs: Dict[str, Any]) -> Dict[str, Any]:
        """
        Args:
            inputs: {
                "topic": str,
                "insights": List[str],
                "insights_text": str,
                "themes": List[str],
                "gaps": str,
                "raw_results": List[dict],
                "sources_count": int,
            }
        Returns:
            {
                "topic": str,
                "final_report": str,     rendered markdown
                "markdown": str,         same, for download
                "sources": List[dict],
                "insights": List[str],
                "sources_count": int,
                "insights_count": int,
            }
        """
        topic = inputs["topic"]
        insights_text = inputs.get("insights_text", "")
        themes = inputs.get("themes", [])
        gaps = inputs.get("gaps", "")
        raw_results = inputs.get("raw_results", [])

        # Generate the main report body
        report_body = self._write_report(topic, insights_text, themes, gaps)

        # Build sources section
        sources_section = self._build_sources_section(raw_results)

        # Assemble full markdown document
        timestamp = datetime.now().strftime("%B %d, %Y")
        full_report = f"""# 🔬 Research Report: {topic}

*Generated on {timestamp} by Multi-Agent Research Assistant*

---

{report_body}

---

## 📚 Sources

{sources_section}

---
*This report was automatically generated by a 3-agent AI pipeline:*
*Search Agent → Analyst Agent → Report Writer Agent*
"""

        return {
            "topic": topic,
            "final_report": full_report,
            "markdown": full_report,
            "sources": raw_results,
            "insights": inputs.get("insights", []),
            "sources_count": inputs.get("sources_count", len(raw_results)),
            "insights_count": len(inputs.get("insights", [])),
        }

    # ── Private helpers ───────────────────────────────────────────────────────

    def _write_report(
        self, topic: str, insights_text: str, themes: List[str], gaps: str
    ) -> str:
        themes_str = "\n".join(f"- {t}" for t in themes) if themes else "Not identified"

        user_prompt = f"""Write a comprehensive research report on the following topic.

Topic: {topic}

Key Themes Identified:
{themes_str}

Research Insights:
{insights_text}

Knowledge Gaps:
{gaps}

---

Structure the report with these sections (use ## headings):
1. Executive Summary (3-4 sentences overview)
2. Key Findings (most important facts and data points)
3. Trends & Analysis (patterns, what the data suggests)
4. Challenges & Limitations (what problems or gaps exist)
5. Conclusion & Recommendations (what should readers do or consider)

Use bullet points where helpful. Be concrete. Avoid vague statements.
"""
        return self._call_llm(WRITER_SYSTEM_PROMPT, user_prompt)

    def _build_sources_section(self, raw_results: List[dict]) -> str:
        if not raw_results:
            return "_No sources available._"
        lines = []
        for i, r in enumerate(raw_results, 1):
            title = r.get("title", "Untitled")
            url = r.get("url", "#")
            snippet = r.get("snippet", "")[:150]
            lines.append(f"{i}. **[{title}]({url})**  \n   _{snippet}..._")
        return "\n\n".join(lines)
